# Generated by Django 5.1.6 on 2025-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uavs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavs',
            name='status',
            field=models.CharField(choices=[('Out Prod', 'Üretimde Değil'), ('In Prod', 'Üretimde')], default='In Prod', max_length=50),
        ),
    ]
