# Generated by Django 5.1.6 on 2025-02-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uavs', '0004_alter_uavs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uavs',
            name='status',
            field=models.CharField(choices=[('In Prod', 'Üretimde'), ('Out Prod', 'Üretimde Değil')], default='In Prod', max_length=50),
        ),
    ]
