# Generated by Django 5.1.6 on 2025-02-21 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('uavs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tail', 'Kuyruk'), ('body', 'Gövde'), ('avionic', 'Aviyonik'), ('wing', 'Kanat')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='uavs.uavs')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'aircraft'), name='unique_part_per_aircraft')],
            },
        ),
    ]
