# Generated by Django 5.1.6 on 2025-02-21 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('wing', 'Kanat Takımı'), ('body', 'Gövde Takımı'), ('tail', 'Kuyruk Takımı'), ('avionics', 'Aviyonik Takımı'), ('assembly', 'Montaj Takımı')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_assemble', models.BooleanField(default=False)),
                ('is_producer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
